### PR TITLE
pt-PT core translation

### PR DESCRIPTION
**Pull request by fgsoftware1**

### CODE REVIEW

**Comment by fgsoftware1** [comment]
done

**Comment by DDShadowRU** [comment]
Thanks

**Comment by fgsoftware1** [comment]
you can merge this i will open more PRs in a future

**Comment by DDShadowRU** [comment]
I will not merge PR into this branch because it will no longer be supported. Now a new version of the mod is being developed from scratch and your developments will be used in the future. If you are interested, you can look at the `bedrock-1.16` branch, but the current progress is at an early stage. Thanks again for your help👍

**Comment by fgsoftware1** [comment]
ok i'll take look

**Comment by fgsoftware1** [comment]
> I will not merge PR into this branch because it will no longer be supported. Now a new version of the mod is being developed from scratch and your developments will be used in the future. If you are interested, you can look at the `bedrock-1.16` branch, but the current progress is at an early stage. Thanks again for your help👍

how translation works on bedrock-1.16? i don't see any translation.js i only see en.properties

**Comment by DDShadowRU** [comment]
> > I will not merge PR into this branch because it will no longer be supported. Now a new version of the mod is being developed from scratch and your developments will be used in the future. If you are interested, you can look at the `bedrock-1.16` branch, but the current progress is at an early stage. Thanks again for your help👍
> 
> how translation works on bedrock-1.16? i don't see any translation.js i only see en.properties

For convenience, the translation is abstracted from the code. To add localization for your language, you need to add the `pt.properties` file to the `langs` directory. But the new version of the mod is not even ready for the alpha version. Don't bother yourself, I'll transfer the translation myself when necessary. So that your efforts are not wasted in vain, I will post a patch to the latest version in the mod browser with your translation within a week.

**Comment by fgsoftware1** [comment]
> > > I will not merge PR into this branch because it will no longer be supported. Now a new version of the mod is being developed from scratch and your developments will be used in the future. If you are interested, you can look at the `bedrock-1.16` branch, but the current progress is at an early stage. Thanks again for your help👍
> > 
> > 
> > how translation works on bedrock-1.16? i don't see any translation.js i only see en.properties
> 
> For convenience, the translation is abstracted from the code. To add localization for your language, you need to add the `pt.properties` file to the `langs` directory. But the new version of the mod is not even ready for the alpha version. Don't bother yourself, I'll transfer the translation myself when necessary. So that your efforts are not wasted in vain, I will post a patch to the latest version in the mod browser with your translation within a week.

thanks

**Pull request merged**
